"""Create update User

Revision ID: 8cfd0a6bfda5
Revises: f02d46e71b59
Create Date: 2026-09-17 22:57:18.771952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cfd0a6bfda5'
down_revision: Union[str, Sequence[str], None] = 'f02d46e71b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('update_a', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'update_a')
    # ### end Alembic commands ###
